# Generated by Django 4.2.11 on 2024-05-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friends_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
    ]
