# Generated by Django 4.2.11 on 2024-05-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='balance_amt',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='balance_outstanding',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='group',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='split_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_2',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='user_expense', max_length=100),
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('Equal', 'Equal'), ('Exact', 'Exact'), ('Percentage', 'Percentage')], default='equal', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.group')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
