# Generated by Django 4.2.11 on 2024-05-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_amount_expense_balance_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesplit',
            name='group',
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.group'),
        ),
    ]
