# Generated by Django 4.2.11 on 2024-05-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0003_remove_expensesplit_group_expense_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesplit',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='user_2',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='expense_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
